# Add the packages you need for this project, possibly using specific versions.
# For example:
#
# packages = [ "nodejs-14_x", "go_1_15", "google-cloud-sdk" ]

# To find the packages, you need to know their names of course. You can search for
# packages like this::
#
# $ nix search nixpkgs nodejs

# Add any environment variables (not considered secret)
#
# [env]
# IN_DEVSHELL = "1"